const Scroll = () => {
    return (
        <div>
            <select className="scroll">
                <option value="DDP 동대문디자인플라자">DDP 동대문디자인플라자</option>
                <option value="경복궁">경복궁</option>
                <option value="경의선숲길">경의선숲길</option>
                <option value="경춘선숲길">경춘선숲길</option>
                <option value="경희궁">경희궁</option>
                <option value="광화문광장">광화문광장</option>
                <option value="국립중앙박물관">국립중앙박물관</option>
                <option value="낙산공원">낙산공원</option>
                <option value="남한산성 북문">남한산성 북문</option>
                <option value="노을공원">노을공원</option>
                <option value="창덕궁">창덕궁</option>
                <option value="망원한강공원">망원한강공원</option>
                <option value="반포대교 달빛무지개분수">반포대교 달빛무지개분수</option>
                <option value="보신각">보신각</option>
                <option value="북악팔각정">북악팔각정</option>
                <option value="북한산국립공원">북한산국립공원</option>
                <option value="북한산성">북한산성</option>
                <option value="삼청동길">삼청동길</option>
                <option value="서대문자연사박물관">서대문자연사박물관</option>
                <option value="서울숲공원">서울숲공원</option>
                <option value="서울함 공원">서울함 공원</option>
                <option value="석촌호수 공원">석촌호수 공원</option>
                <option value="선유도공원">선유도공원</option>
                <option value="양재시민의숲">양재시민의숲</option>
                <option value="월드컵공원">월드컵공원</option>
                <option value="인사동거리">인사동거리</option>
                <option value="인왕산">인왕산</option>
                <option value="전쟁기념관">전쟁기념관</option>
                <option value="천주교 절두산 순교성지">천주교 절두산 순교성지</option>
                <option value="중앙공원">중앙공원</option>
                <option value="창의문">창의문</option>
                <option value="청계천">청계천</option>
                <option value="충무아트센터">충무아트센터</option>
                <option value="탑골공원">탑골공원</option>
                <option value="평화의공원">평화의공원</option>
                <option value="하늘공원">하늘공원</option>
                <option value="한강대교">한강대교</option>
                <option value="해운대해수욕장">해운대해수욕장</option>
                <option value="행주산성">행주산성</option>
                <option value="홍대거리">홍대거리</option>
                <option value="북촌한옥마을">북촌한옥마을</option>
                <option value="국립민속박물관">국립민속박물관</option>
                <option value="창경궁">창경궁</option>
                <option value="이화동 벽화마을">이화동 벽화마을</option>
                <option value="남대문시장">남대문시장</option>
                <option value="국립고궁박물관">국립고궁박물관</option>
                <option value="광명동굴">광명동굴</option>
                <option value="헤이리 예술마을">헤이리 예술마을</option>
                <option value="양화한강공원">양화한강공원</option>
                <option value="화담숲">화담숲</option>
                <option value="반포한강공원">반포한강공원</option>
                <option value="광장 시장">광장 시장</option>
                <option value="서울로7017">서울로7017</option>
                <option value="여의도공원">여의도공원</option>
                <option value="천지연폭포">천지연폭포</option>
                <option value="제주동문시장">제주동문시장</option>
                <option value="몽마르뜨공원">몽마르뜨공원</option>
                <option value="한국 근현대사박물관">한국 근현대사박물관</option>
                <option value="서울 트릭아이뮤지엄 Trickeye Museum">서울 트릭아이뮤지엄 Trickeye Museum</option>
                <option value="남산 공원">남산 공원</option>
                <option value="대림미술관">대림미술관</option>
                <option value="문화비축기지">문화비축기지</option>
                <option value="프로방스 마을">프로방스 마을</option>
                <option value="달전망대">달전망대</option>
                <option value="남산골 한옥마을">남산골 한옥마을</option>
                <option value="낙성대공원">낙성대공원</option>
                <option value="파리공원">파리공원</option>
                <option value="청계 광장">청계 광장</option>
                <option value="인천 차이나타운">인천 차이나타운</option>
                <option value="영종대교기념관">영종대교기념관</option>
                <option value="물의정원">물의정원</option>
                <option value="송월동 동화마을">송월동 동화마을</option>
                <option value="수종사">수종사</option>
                <option value="도라전망대">도라전망대</option>
                <option value="청연루">청연루</option>
                <option value="용두암">용두암</option>
                <option value="용연구름다리">용연구름다리</option>
                <option value="용머리해안">용머리해안</option>
                <option value="섭지코지">섭지코지</option>
                <option value="정방폭포">정방폭포</option>
                <option value="서귀포매일올레시장">서귀포매일올레시장</option>
                <option value="만장굴">만장굴</option>
                <option value="한림공원">한림공원</option>
                <option value="성산 일출봉">성산 일출봉</option>
                <option value="제주조천">제주조천</option>
                <option value="스위스마을">스위스마을</option>
                <option value="제주불빛정원">제주불빛정원</option>
                <option value="제주절물자연휴양림">제주절물자연휴양림</option>
                <option value="답다니탑망대">답다니탑망대</option>
                <option value="쇠소깍">쇠소깍</option>
                <option value="사라봉공원">사라봉공원</option>
                <option value="천제연폭포">천제연폭포</option>
                <option value="한라수목원">한라수목원</option>
                <option value="새연교">새연교</option>
                <option value="시흥갯골생태공원">시흥갯골생태공원</option>
                <option value="경암동철길마을 시작점">경암동철길마을 시작점</option>
                <option value="장항스카이워크">장항스카이워크</option>
                <option value="용인자연 휴양림">용인자연 휴양림</option>
                <option value="배곧생명공원">배곧생명공원</option>
                <option value="자만벽화마을">자만벽화마을</option>
                <option value="벽골제">벽골제</option>
                <option value="덕진공원">덕진공원</option>
                <option value="1913 송정역시장">1913 송정역시장</option>
                <option value="진도타워">진도타워</option>
                <option value="백제문화단지">백제문화단지</option>
                <option value="감천문화마을">감천문화마을</option>
                <option value="대전스카이로드">대전스카이로드</option>
                <option value="목포 갓바위 (천연기념물 제500호)">목포 갓바위 (천연기념물 제500호)</option>
                <option value="정선아리랑시장">정선아리랑시장</option>
                <option value="모래시계공원">모래시계공원</option>
                <option value="만천하스카이워크">만천하스카이워크</option>
                <option value="청풍문화재단지">청풍문화재단지</option>
                <option value="도담삼봉">도담삼봉</option>
                <option value="송도구름산책로">송도구름산책로</option>
                <option value="청풍호관광모노레일">청풍호관광모노레일</option>
                <option value="168계단">168계단</option>
                <option value="부산타워">부산타워</option>
                <option value="메타세콰이아가로수길">메타세콰이아가로수길</option>
                <option value="춘향테마파크">춘향테마파크</option>
                <option value="진주성">진주성</option>
                <option value="흰여울마을">흰여울마을</option>
                <option value="주산지(注山池)">주산지(注山池)</option>
                <option value="문경새재오픈세트장">문경새재오픈세트장</option>
            </select>
            <br/>
        </div>


    )
}
export default Scroll